name: Release to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    # If you configured an environment in the PyPI pending publisher, uncomment the next line:
    # environment: release
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: pip install build
      - run: python -m build --outdir pypi_dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: pypi_dist/
          verbose: true
